accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
  
build:
  binary: "anoned"
init:
  home: "$HOME/.anoned"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "anoned_1711-1"
  app_state:
    staking:
      params:
        bond_denom: "uone"
    mint:
      params:
        mint_denom: "uone"
    crisis:
      constant_fee:
        denom: "uone"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "uone"
    evm:
      params:
        evm_denom: "uone"
