# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Deploy - Test

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: asd
      run: ls -a /home/runner/work/anone/anone

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build the web
      run: |
        cd vue
        npm install 
        npm run build
        ls -a
    
    - name: Compress /dist
      run: |
        cd vue
        tar -zcvf dist.tar.gz /dist

    - name: Transfer /dist folder to server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: vue/dist
        remote: /root/dist
        host: 49.12.223.158
        username: root
        password: 1
